$('#myTab a').click(function (e) { 
    e.preventDefault(); $(this).tab('show'); 
});

$('[rel=tooltip]').tooltip();

$('[rel=datetime]').datetimepicker({ 
    pickTime: false 
});

var arrayNames = [];
var arrayIds = {};

$("#tbSolicitadoPor").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/BuscarSolicitadoPor", data: "{'cod_aseguradora': '" + $('#ddlAseguradora').val() + "', 'buscar': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbSolicitadoPorCod').val('-1'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbSolicitadoPorCod').val(arrayIds[item].cod_auto); return item; } });
$("#tbAseguradoNombre").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getAsegurado", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbAseguradoCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombres] = value; arrayNames.push(value.nombres); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbAseguradoCodAuto').val(arrayIds[item].cod_auto); $('#tbAseguradoCedula').val(arrayIds[item].cedula); return item; } });
$("#tbRCNombre").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getAsegurado", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbRCCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombres] = value; arrayNames.push(value.nombres); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbRCCodAuto').val(arrayIds[item].cod_auto); $('#tbRCCedula').val(arrayIds[item].cedula); return item; } });
$("#tbAgregarRC").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getAsegurado", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbAgregarRCCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombres] = value; arrayNames.push(value.nombres); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbAgregarRCCodAuto').val(arrayIds[item].cod_auto); $('#tbAgregarRCCedula').val(arrayIds[item].cedula); return item; } });
$("#tbTallerNombre").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getTaller", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbTallerCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbTallerCodAuto').val(arrayIds[item].cod_auto); $('#tbTallerContacto').val(arrayIds[item].contacto); $('#tbTallerTelefono').val(arrayIds[item].telefono); $('#tbTallerUbicacion').val(arrayIds[item].ubicacion); $('#tbTallerUbicacionCodAuto').val(arrayIds[item].cod_ciudad); $('#tbTallerDireccion').val(arrayIds[item].direccion); var sel = document.getElementById('ddlTallerZona'); for (var i, j = 0; i = sel.options[j]; j++) { if (i.value == arrayIds[item].cod_zona) { sel.selectedIndex = j; break; } } return item; } });
$("#tbRCTallerNombre").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getTaller", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbRCTallerCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbRCTallerCodAuto').val(arrayIds[item].cod_auto); $('#tbRCTallerContacto').val(arrayIds[item].contacto); $('#tbRCTallerTelefono').val(arrayIds[item].telefono); $('#tbRCTallerUbicacion').val(arrayIds[item].ubicacion); $('#tbRCTallerUbicacionCodAuto').val(arrayIds[item].cod_ciudad); $('#tbRCTallerDireccion').val(arrayIds[item].direccion); var sel = document.getElementById('ddlRCTallerZona'); for (var i, j = 0; i = sel.options[j]; j++) { if (i.value == arrayIds[item].cod_zona) { sel.selectedIndex = j; break; } } return item; } });
$("#tbAgregarTaller").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getTaller", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbAgregarTallerCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbAgregarTallerCodAuto').val(arrayIds[item].cod_auto); $('#tbAgregarTallerContacto').val(arrayIds[item].contacto); $('#tbAgregarTallerTelefono').val(arrayIds[item].telefono); $('#tbAgregarTallerUbicacion').val(arrayIds[item].ubicacion); $('#tbAgregarTallerUbicacionCodAuto').val(arrayIds[item].cod_ciudad); $('#tbAgregarTallerDireccion').val(arrayIds[item].direccion); var sel = document.getElementById('ddlAgregarTallerZona'); for (var i, j = 0; i = sel.options[j]; j++) { if (i.value == arrayIds[item].cod_zona) { sel.selectedIndex = j; break; } } return item; } });
$("#tbTallerUbicacion").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getUbicacionGeografica", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbTallerUbicacionCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbTallerUbicacionCodAuto').val(arrayIds[item].cod_ciudad); return item; } });
$("#tbRCTallerUbicacion").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getUbicacionGeografica", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbRCTallerUbicacionCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbRCTallerUbicacionCodAuto').val(arrayIds[item].cod_ciudad); return item; } });
$("#tbAgregarTallerUbicacion").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getUbicacionGeografica", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbAgregarTallerUbicacionCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbAgregarTallerUbicacionCodAuto').val(arrayIds[item].cod_ciudad); return item; } });
$("#tbRepuestoManoObra").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getRepuesto", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbRepuestoManoObraCodAuto').val('0'); $('#tbRepuestoManoObraCodTipo').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbRepuestoManoObraCodAuto').val(arrayIds[item].cod_auto); $('#tbRepuestoManoObraCodTipo').val(arrayIds[item].cod_catalogo_tipo_repuesto); return item; } });
$("#tbRepuestoManoObra").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getRepuesto", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbRepuestoManoObraCodAuto').val('0'); $('#tbRepuestoManoObraCodTipo').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbRepuestoManoObraCodAuto').val(arrayIds[item].cod_auto); $('#tbRepuestoManoObraCodTipo').val(arrayIds[item].cod_catalogo_tipo_repuesto); return item; } });
$("#tbVehiculoMarca").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getMarcaVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbVehiculoModelo").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getModeloVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbVehiculoColor").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getColorVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbRCVehiculoMarca").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getMarcaVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbRCVehiculoModelo").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getModeloVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbRCVehiculoColor").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getColorVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbAgregarVehiculoMarca").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getMarcaVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbAgregarVehiculoModelo").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getModeloVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbAgregarVehiculoColor").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getColorVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });

function AjaxError(result) {
    alert("ERROR " + result.status + ' ' + result.statusText); 
}