$('#myTab a').click(function (e) { e.preventDefault(); $(this).tab('show'); });
$('[rel=tooltip]').tooltip();
$('[rel=datetime]').datetimepicker({ pickTime: false });

var arrayNames = [];
var arrayIds = {};

$("#tbAseguradoNombre").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getAsegurado", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbAseguradoCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombres] = value; arrayNames.push(value.nombres); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbAseguradoCodAuto').val(arrayIds[item].cod_auto); $('#tbAseguradoCedula').val(arrayIds[item].cedula); $('#tbAseguradoContacto').val(arrayIds[item].contacto); $('#tbAseguradoContactoTelefono').val(arrayIds[item].telefono_contacto); $('#tbTelefonoTrabajo').val(arrayIds[item].telefono_trabajo); $('#tbTelefonoMovil').val(arrayIds[item].telefono_movil); return item; } });
$("#tbInspeccionUbicacion").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getUbicacionGeografica", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbInspeccionUbicacionCodCiudad').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbInspeccionUbicacionCodCiudad').val(arrayIds[item].cod_ciudad); return item; } });
$("#tbInmuebleUbicacion").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getUbicacionGeografica", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbInmuebleUbicacionCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbInmuebleUbicacionCodAuto').val(arrayIds[item].cod_ciudad); return item; } });
$("#tbMaquinaUbicacion").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getUbicacionGeografica", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbMaquinaUbicacionCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbMaquinaUbicacionCodAuto').val(arrayIds[item].cod_ciudad); return item; } });
$("#tbAgregarDetalleInmuebleUbicacion").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getUbicacionGeografica", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbAgregarDetalleInmuebleUbicacionCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbAgregarDetalleInmuebleUbicacionCodAuto').val(arrayIds[item].cod_ciudad); return item; } });
$("#tbAgregarDetalleMaquinaUbicacion").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getUbicacionGeografica", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbAgregarDetalleMaquinaUbicacionCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbAgregarDetalleMaquinaUbicacionCodAuto').val(arrayIds[item].cod_ciudad); return item; } });
$("#tbVehiculoMarca").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getMarcaVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbVehiculoModelo").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getModeloVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbVehiculoColor").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getColorVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbAgregarDetalleVehiculoMarca").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getMarcaVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbAgregarDetalleVehiculoModelo").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getModeloVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });
$("#tbAgregarDetalleVehiculoColor").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../WebService/WSAjustes.asmx/getColorVehiculo", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { return item; } });

function AjaxError(result) { alert("ERROR " + result.status + ' ' + result.statusText); }