$('#myTab a').click(function (e) { 
    e.preventDefault(); $(this).tab('show'); 
});

$('[rel=tooltip]').tooltip();

$('[rel=datetime]').datetimepicker({ 
    pickTime: false 
});

var arrayNames = [];
var arrayIds = {};

$("#tbSolicitadoPor").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../../WebService/WSAjustes.asmx/BuscarSolicitadoPor", data: "{'cod_aseguradora': '32', 'buscar': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbSolicitadoPorCod').val('-1'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbSolicitadoPorCod').val(arrayIds[item].cod_auto); return item; } });
$("#tbAsegurado").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../../WebService/WSAjustes.asmx/getAsegurado", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbAseguradoCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombres] = value; arrayNames.push(value.nombres); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbAseguradoCodAuto').val(arrayIds[item].cod_auto); $('#tbAseguradoCedula').val(arrayIds[item].cedula); $('#tbAseguradoContacto').val(arrayIds[item].contacto); $('#tbAseguradoTelefonoDomicilio').val(arrayIds[item].telefono_contacto); $('#tbAseguradoTelefonoTrabajo').val(arrayIds[item].telefono_trabajo); $('#tbAseguradoTelefonoMovil').val(arrayIds[item].telefono_movil); return item; } });
$("#tbTallerNombre").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../../WebService/WSAjustes.asmx/getTaller", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbTallerCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbTallerCodAuto').val(arrayIds[item].cod_auto); $('#tbTallerContacto').val(arrayIds[item].contacto); $('#tbTallerTelefono').val(arrayIds[item].telefono); $('#tbTallerUbicacion').val(arrayIds[item].ubicacion); $('#tbTallerCodCiudad').val(arrayIds[item].cod_ciudad); $('#tbTallerDistancia').val(arrayIds[item].distancia); $('#tbTallerDireccion').val(arrayIds[item].direccion); var sel = document.getElementById('ddlTallerZona'); for (var i, j = 0; i = sel.options[j]; j++) { if (i.value == arrayIds[item].cod_zona) { sel.selectedIndex = j; break; } } return item; } });
$("#tbTallerUbicacion").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../../WebService/WSAjustes.asmx/getUbicacionGeografica", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbTallerCodCiudad').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbTallerCodCiudad').val(arrayIds[item].cod_ciudad); return item; } });
$("#tbRCAfectado").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../../WebService/WSAjustes.asmx/getAsegurado", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbRCAfectadoCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombres] = value; arrayNames.push(value.nombres); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbRCAfectadoCodAuto').val(arrayIds[item].cod_auto); $('#tbRCAfectadoCedula').val(arrayIds[item].cedula); $('#tbRCAfectadoContacto').val(arrayIds[item].contacto); $('#tbRCAfectadoTelefonoDomicilio').val(arrayIds[item].telefono_contacto); $('#tbRCAfectadoTelefonoTrabajo').val(arrayIds[item].telefono_trabajo); $('#tbRCAfectadoTelefonoMovil').val(arrayIds[item].telefono_movil); return item; } });
$("#tbRCTallerNombre").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../../WebService/WSAjustes.asmx/getTaller", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbRCTallerCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbRCTallerCodAuto').val(arrayIds[item].cod_auto); $('#tbRCTallerContacto').val(arrayIds[item].contacto); $('#tbRCTallerTelefono').val(arrayIds[item].telefono); $('#tbRCTallerUbicacion').val(arrayIds[item].ubicacion); $('#tbRCTallerUbicacionCodAuto').val(arrayIds[item].cod_ciudad); $('#tbRCTallerDistancia').val(arrayIds[item].distancia); $('#tbRCTallerDireccion').val(arrayIds[item].direccion); var sel = document.getElementById('ddlRCTallerZona'); for (var i, j = 0; i = sel.options[j]; j++) { if (i.value == arrayIds[item].cod_zona) { sel.selectedIndex = j; break; } } return item; } });
$("#tbRCTallerUbicacion").typeahead({ source: function (query, process) { return $.ajax({ type: "POST", url: "../../WebService/WSAjustes.asmx/getUbicacionGeografica", data: "{'nombre': '" + query + "'}", contentType: "application/json; charset=utf-8", dataType: "json", success: function (jsonData) { $('#tbRCTallerUbicacionCodAuto').val('0'); arrayNames = []; arrayIds = {}; var jsonArray = jQuery.parseJSON(jsonData.d); $.each(jsonArray, function (key, value) { arrayIds[value.nombre] = value; arrayNames.push(value.nombre); }); return process(arrayNames); }, error: AjaxError }); }, updater: function (item) { $('#tbRCTallerUbicacionCodAuto').val(arrayIds[item].cod_ciudad); return item; } });

function AjaxError(result) {
    alert("ERROR " + result.status + ' ' + result.statusText);
} 
